# Generated by Django 3.2.8 on 2022-02-15 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicbody', '0039_publicbody_alternative_emails'),
        ('organization', '0001_initial'),
        ('cms', '0022_auto_20180620_1551'),
        ('froide_govplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentplan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='governmentplanupdate',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='GovernmentPlansCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='froide_govplan_governmentplanscmsplugin', serialize=False, to='cms.cmsplugin')),
                ('count', models.PositiveIntegerField(default=1, help_text='0 means all the plans', verbose_name='number of plans')),
                ('offset', models.PositiveIntegerField(default=0, help_text='number of plans to skip from top of list', verbose_name='offset')),
                ('template', models.CharField(blank=True, choices=[('froide_govplan/plugins/default.html', 'Normal')], help_text='template used to display the plugin', max_length=250, verbose_name='template')),
                ('categories', models.ManyToManyField(blank=True, to='publicbody.Category', verbose_name='categories')),
                ('government', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='froide_govplan.government')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
