# Generated by Django 3.2.12 on 2022-03-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_govplan", "0007_auto_20220314_1422"),
    ]

    operations = [
        migrations.AddField(
            model_name="governmentplan",
            name="proposals",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
