# Generated by Django 3.2.12 on 2022-03-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_govplan', '0009_governmentplanupdatescmsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentplanscmsplugin',
            name='extra_classes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
