# Generated by Django 3.2.12 on 2022-05-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_govplan', '0010_governmentplanscmsplugin_extra_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentplan',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
