# Generated by Django 4.1.4 on 2023-02-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("publicbody", "0043_merge_20221019_1020"),
        ("georegion", "0011_georegion_invalid_on"),
        ("froide_govplan", "0011_governmentplan_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="government",
            name="georegion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="georegion.georegion",
                verbose_name="georegion",
            ),
        ),
        migrations.AlterField(
            model_name="government",
            name="jurisdiction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="publicbody.jurisdiction",
                verbose_name="jurisdiction",
            ),
        ),
        migrations.AlterField(
            model_name="governmentplanscmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="governmentplanscmsplugin",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("froide_govplan/plugins/default.html", "Normal"),
                    ("froide_govplan/plugins/progress.html", "Progress"),
                    ("froide_govplan/plugins/progress_row.html", "Progress Row"),
                    ("froide_govplan/plugins/time_used.html", "Time used"),
                    ("froide_govplan/plugins/card_cols.html", "Card columns"),
                    ("froide_govplan/plugins/search.html", "Search"),
                ],
                help_text="template used to display the plugin",
                max_length=250,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="governmentplansectionscmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="governmentplanupdatescmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
