# Generated by Django 4.2.16 on 2025-01-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "froide_govplan",
            "0012_government_georegion_alter_government_jurisdiction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="government",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
    ]
