# Generated by Django 5.2.1 on 2025-05-24 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("froide_govplan", "0013_government_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="governmentplansection",
            name="content_placeholder",
        ),
    ]
